// export const images = [
//   "/tech-stack/typescript.jpg",
//   "tech-stack/JavaScript.jpg",
//   "tech-stack/react.jpg",
//   "tech-stack/next.jpg",
//   "tech-stack/Tailwind.jpg",
//   "tech-stack/sqlite.jpg",
//   "tech-stack/node.jpg",
//   "tech-stack/github.jpg",
//   "tech-stack/git.jpg",
//   "tech-stack/html.jpg",
//   "tech-stack/css.jpg",
//   "tech-stack/mongodb.jpg",
//   "tech-stack/sqlite.jpg",
//   "tech-stack/node.jpg",
//   "tech-stack/github.jpg",
//   "tech-stack/git.jpg",
// ];

// export const imageProtifolio1 = [
//   "/portifolio/1.png",
//   "/portifolio/20.png",
//   "/portifolio/3.png",
//   "/portifolio/19.png",
//   "/portifolio/5.png",
//   "/portifolio/18.png",
//   "/portifolio/7.png",
//   "/portifolio/17.png",
//   "/portifolio/9.png",
//   "/portifolio/16.png",
//   "/portifolio/2.png",
//   "/portifolio/11.png",
//   "/portifolio/4.png",
//   "/portifolio/12.png",
//   "/portifolio/6.png",
//   "/portifolio/13.png",
//   "/portifolio/8.png",
//   "/portifolio/14.png",
//   "/portifolio/10.png",
//   "/portifolio/15.png",
// ];
export const firstLineImagae = [
  "/tech-stack/Deno.png",
  "/tech-stack/Express.png",
  "/tech-stack/Git.png",
  "/tech-stack/GitHub.png",
  "/tech-stack/HTML5.png",
  "/tech-stack/JavaScript.png",
  "/tech-stack/Jest.png",
  "/tech-stack/Material UI.png",
];
export const SecondLineImagae = [
  "/tech-stack/MongoDB.png",
  "/tech-stack/Mongoose.js.png",
  "/tech-stack/Next.js.png",
  "/tech-stack/Node.js.png",
  "/tech-stack/Nodemon.png",
  "/tech-stack/PostgresSQL.png",
  "/tech-stack/Postman.png",
  "/tech-stack/React.png",
  "/tech-stack/Redux.png",
];
export const ThiredLineImagae = [
  "/tech-stack/Redis.png",
  "/tech-stack/SQLite.png",
  "/tech-stack/Tailwind CSS.png",
  "/tech-stack/TypeScript.png",
  "/tech-stack/Vercel.png",
  "/tech-stack/Vite.js.png",
  "/tech-stack/WebStorm.png",
  "/tech-stack/Bun.png",
  // "/tack-stack/Jest.png",
  // "/tack-stack/MaterialUI.png",
];
